manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: pete
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: pete
      revision: stephen/split-encoder
      import: app/west.yml
  self:
    path: config
